stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo 'Building...'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

test:
  stage: test
  script:
    - echo 'Testing...'

deploy:
  stage: deploy
  script:
    - echo 'Deploying...'
